### ISSUE TITLE
Update page: Emptying a Database

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#101]
File: [server/empty-database.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/empty-database.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Add some text about doing first a backup (and a breafly explanation and link to the Backup section / database backup)
- [ ] Add a section on how to delete all the database tables and start a new WordPress installation

**Comment by javiercasares** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/issues/779
