### ISSUE TITLE
Update page: Nginx

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#103]
File: [server/nginx.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/nginx.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Update the config files for nginx 1.18+
- [ ] Use HTTPS by default
- [ ] Create a specific section for Cache Plugins (WP Super Cache, W3 Total Cache...)
- [ ] Create a specific section for Popular Plugins (Yoast...)
- [ ] Using nginx as a reverse proxy

**Comment by javiercasares** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/issues/751

**Comment by daniel-fahl** [comment]
I was about to set up Wordpress using nginx, but this page (and it's apparent source from easyengine.io) appear to be very outdated, for wp versions <3.5 (judging by the reference of the `blogs.dir` directory, now known as `/uploads/sites/...`.

Sadly, I now decided against using nginx as my web server despite actually being really interested in it, just because it seems the official Wordpress documentation is a) heavily biased, since it's basically copy & pasted from rtCamp / EasyEngine, and b) not reliable since it hasn't been kept up to date since over 10 years.

As I don't have any experience hosting Wordpress reliably with nginx, I am not sure how I could assist you with updating the documentation. Let me know if I can be of any help.

Thanks and all the best!
