### ISSUE TITLE
Update page: Finding Server Info

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#104]
File: [server/server-info.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/server-info.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Using WordPress Site Health
- [ ] Using Linux CLI commands
