### ISSUE TITLE
Update page: Web Servers

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#105]
File: [server/web-server.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/web-server.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Add some Apache HTTPD information
- [ ] Add some LiteSpeed Web Server information
- [ ] Add some OpenLiteSpeed information
- [ ] Add some link to the [Hosting Handbook](https://make.wordpress.org/hosting/handbook/server-environment/#web-server)

**Comment by javiercasares** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/issues/767
