### ISSUE TITLE
Update page: Site Architecture (v1.5)

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#113]
File: [wordpress/site-architecture.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/site-architecture.md)

This page needs a general review and update.

Probably this page will need a big full redo with all the new files and structure. An update in the core structure is needed.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Check the Classic Themes structure
- [ ] Create a new Blocks Themes structure
