### ISSUE TITLE
Update page: Update Services

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#114]
File: [wordpress/update-services.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/update-services.md)

This page needs a general review and update.

Also, there are new technologies to apply here.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Check if the ping providers are working
- [ ] Add information about new technologies and link to search in plugins

**Comment by usarral** [comment]
Assign me
