### ISSUE TITLE
Update page: Migrating WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#133]
File: [upgrade/migrating.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/upgrade/migrating.md)

This page needs a general review and update.

This page requires a Headers structure review.

Moreover, maybe try not to use the “functions.php” in themes to do redirections or “plugin work”.

This page potentially needs to be split in some subsections / subpages.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Check the Headers structure (H1 - H6)
- [ ] Avoid suggesting theme “functions.php” as “plugin's work”
- [ ] Split subsections in new pages
