### ISSUE TITLE
Update page: Upgrading WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#136]
File: [upgrade/upgrading.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/upgrade/upgrading.md)

This page needs a general review and update.

Needs to have some different parts. One, the simple update via the Admin panel, Two, the manual update via FTP.

Furthermore, probably, check the upgrade via WP Toolkit, or refer to it.

Plus, refer to [Upgrading (very old) WordPress](https://make.wordpress.org/hosting/handbook/upgrading/), maybe [moving all this content from the Hosting Handbook (in Markdown)](https://github.com/WordPress/hosting-handbook/blob/main/upgrading.md).

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Review all the process, both simple (admin) and complex (FTP / SQL)
- [ ] Upgrading (very old) WordPress
