### ISSUE TITLE
Update page: Multisite Network Administration

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#139]
File: [multisite/administration.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/multisite/administration.md)

This page needs a general review and update.

Delete the references to WordPress MU and old WordPress versions.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Delete references to WordPress MU.
- [ ] Update references for WordPress > 4.1
