### ISSUE TITLE
Update page: Running a Development Copy of WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#95]
File: [before-install/development.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/before-install/development.md)

This page needs a general review and update.

Please, if you add documentation from another wordpress.org page, please, add it in the Changelog or in the comments of this Issue.

### ToDo

- [ ] General review and updating
- [ ] Check [Installing a Local Server](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/)
- [ ] Check [wp-env: Simple Local Environments for WordPress](https://make.wordpress.org/core/2020/03/03/wp-env-simple-local-environments-for-wordpress/)
- [ ] Check [WordPress Local Environment](https://make.wordpress.org/core/2019/08/05/wordpress-local-environment/)
- [ ] Check [Write a tutorial for setting up a local dev environment](https://make.wordpress.org/core/2011/09/18/write-a-tutorial-for-setting-up-a-local-dev-environment/)
- [ ] Check [WordPress development environment](https://make.wordpress.org/core/2021/11/24/wordpress-development-environment/)
