### ISSUE TITLE
Update page: How to install WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#96]
File: [before-install/howto-install.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/before-install/howto-install.md)

This page needs a general review and update.

Please, if you add documentation from another wordpress.org page, please, add it in the Changelog or in the comments of this Issue.

### ToDo

- [ ] General review and updating

- [ ] Link some sections to their main documentation pages (phpMyAdmin, Create database, wp-config, upload files with FTP client or FileZilla)
- [ ] Delete the Installing WordPress at popular Hosting Companies, and refer to the new [before-install/popular-providers.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/before-install/popular-providers.md) page
- [ ] Add the installation for WP Toolkit (for [Plesk](https://docs.plesk.com/en-US/obsidian/reseller-guide/website-management/wordpress-toolkit.73391/) and [cPanel](https://docs.cpanel.net/knowledge-base/cpanel-developed-plugins/wordpress-toolkit/)).

**Comment by pieteee** [comment]
Hello @javiercasares I'd like to work on this. Can you please assign this to me? Thank you!
